categories:
  I_Love_You:
    - "A romantic sunset scene where a couple is holding hands on a beach, waves gently touching their feet, with 'I Love You' written in the sky with soft clouds."
    - "A cozy indoor setting with dim fairy lights, a table set for two with candles and roses, and a small handwritten note saying 'I Love You'."
  
  Good_Morning:
    - "A bright, cheerful morning scene with golden sunlight streaming through a window, a steaming cup of coffee on the table, and a handwritten 'Good Morning' note beside it."
    - "A beautiful sunrise over a lush green valley, birds flying in the sky, and a warm, peaceful ambiance that radiates positivity."
  
  Good_Night:
    - "A starry night with a full moon casting a soft glow over a quiet countryside, a cozy house with warm lights in the distance, and 'Good Night' written in soft clouds."
    - "A peaceful bedroom scene with dim lighting, a comfy bed with a book and a mug of hot chocolate on the side table, creating a relaxing nighttime atmosphere."
  
  Take_Care:
    - "A warm, comforting image of a person wrapping a soft blanket around another, symbolizing care and affection, with 'Take Care' subtly written in the background."
    - "A scenic nature trail with a person walking gently, enjoying the fresh air, a subtle message of self-care and well-being."
  
  Happy_Birthday:
    - "A vibrant birthday party setup with colorful balloons, a beautifully decorated cake with candles, and a joyful atmosphere filled with confetti and laughter."
    - "A close-up of hands presenting a beautifully wrapped gift, with a birthday card on top that says 'Happy Birthday' in elegant handwriting."
  
  Happy_Anniversary:
    - "A romantic dinner setup with candles, wine glasses clinking, and a soft-focus background of a happy couple celebrating their love."
    - "A scrapbook with old photographs, love letters, and dried flowers, symbolizing a journey of love and commitment, with 'Happy Anniversary' elegantly inscribed."
  
  Sorry:
    - "A heartfelt scene of a person holding a small 'I'm Sorry' note with a bouquet of flowers, symbolizing an apology filled with sincerity."
    - "A soft and warm image of two hands holding each other in reconciliation, with a blurred background and a peaceful, forgiving atmosphere."
  
  Thank_You:
    - "A close-up of a handwritten 'Thank You' card on a rustic wooden table, surrounded by flowers and a small gift, radiating warmth and gratitude."
    - "A glowing sunset where a person is receiving a heartfelt hug from another, conveying deep appreciation and gratitude."
